server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.120:8761/eureka,http://192.168.1.121:8761/eureka,http://192.168.1.122:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: SPRING-CLOUD-HYSTRIX-ZUUL
zuul:
  ignored-services: '*'
  routes:
    SPRING-CLOUD-EUREKA-SERVER: /eureka/**
    turbine:
      path: /turbine/**
      service-id: SPRING-CLOUD-HYSTRIX-TURBINE
    spring-cloud-hystrix-zuul:
      path: /zuul/**
      url: http://localhost:8082/
    db:
      path: /db/**
      service-id: SPRING-CLOUD-HYSTRIX-DB
      strip-prefix: false
  prefix: /zuul
  strip-prefix: false
logging:
  level:
    root: info
    org.springframework.cloud.netflix.zuul.filters: debug
db:
  ribbon:
    listOfServices: http://localhost:8082/,http://localhost:8083/
sidecar:
  hostname: http://192.168.1.110:8082/
  health-uri: http://localhost:8082/actuator/health
  home-page-uri: http://localhost:8082/
  ip-address: 192.168.1.110
  port: 8082